// Initial Database exported from FirePump.xlsx
const INITIAL_USERS = [
  {
    "Username": "johporadmin",
    "Password": "Admin0123456789",
    "Rank": "P3",
    "PermitDo": 3,
    "EmName": "Halls"
  },
  {
    "Username": "LeaderLinePD1",
    "Password": "PD1",
    "Rank": "P1",
    "PermitDo": 1,
    "EmName": "Jort"
  }
];

const INITIAL_TANKS = [
  {
    "FireTank": "EX01",
    "Types": "Low-pressure water formula",
    "Weight (lb)": 10,
    "Area": "Solar WH",
    "Inuse": "01/01/2022",
    "Lastcheck": "2026-09-29 17:57",
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": "Ready",
    "TankStatus": true,
    "Exptank": "4ปี",
    "PicTank": "uploads/tanks/EX01_PicTank_QRCode_JDE_Peets_scml.png",
    "PicArea": null,
    "Inspector": "Jort"
  },
  {
    "FireTank": "EX02",
    "Types": "Dry Chemical",
    "Weight (lb)": 20,
    "Area": "LPG station",
    "Inuse": null,
    "Lastcheck": "2026-09-29 18:38",
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": "Ready",
    "TankStatus": true,
    "Exptank": null,
    "PicTank": "uploads/tanks/EX02_PicTank_QRCode_JDE_Peets_scml.png",
    "PicArea": null,
    "Inspector": "Jort"
  },
  {
    "FireTank": "EX03",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Checker (Production)",
    "Inuse": "01/01/2012",
    "Lastcheck": "2026-09-29 16:10",
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": "Ready",
    "TankStatus": true,
    "Exptank": "14ปี",
    "PicTank": "uploads/tanks/EX03_PicTank_QRCode_JDE_Peets_scml.png",
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX04",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Equipment Washing Room",
    "Inuse": "01/01/2013",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "13ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX05",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Hot work (in)",
    "Inuse": "01/01/2016",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "10ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX06",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Hot work",
    "Inuse": "01/01/2019",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "7ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX07",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Washroom PD2",
    "Inuse": "01/01/2017",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "9ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX08",
    "Types": "Dry Chemical",
    "Weight (lb)": 20,
    "Area": "Rework PD1",
    "Inuse": "01/01/2005",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "21ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX09",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "Hazardous waste point PD1",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX10",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "SAP PD1",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX11",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "MDB2",
    "Inuse": "01/01/2019",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "7ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX12",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 20,
    "Area": "MDB2 (in)",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX13",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "Canteen",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX14",
    "Types": "Low-pressure water formula",
    "Weight (lb)": 10,
    "Area": "Office 2nd Floor",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX15",
    "Types": "Low-pressure water formula",
    "Weight (lb)": 10,
    "Area": "Office 2nd Floor",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX16",
    "Types": "Dry Chemical",
    "Weight (lb)": 20,
    "Area": "Document room 3rd Floor",
    "Inuse": "01/01/2006",
    "Lastcheck": "2026-09-29 17:54",
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": "Ready",
    "TankStatus": true,
    "Exptank": "20ปี",
    "PicTank": "uploads/tanks/EX16_PicTank_QRCode_JDE_Peets_scml.png",
    "PicArea": null,
    "Inspector": "Jort"
  },
  {
    "FireTank": "EX17",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "3rd Floor",
    "Inuse": "01/01/2021",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "5ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX18",
    "Types": "CO2",
    "Weight (lb)": 0,
    "Area": "AHU 3rd Floor",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX19",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH ",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX20",
    "Types": "Low-pressure water formula",
    "Weight (lb)": 10,
    "Area": "WH gennerator solar",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX21",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH ",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX22",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH ",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX23",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH ",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX24",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH ",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX25",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH Bluk loading",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX26",
    "Types": "Dry Chemical",
    "Weight (lb)": 0,
    "Area": "WH (Construction zone)",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX27",
    "Types": "Dry Chemical",
    "Weight (lb)": 0,
    "Area": "WH (Construction zone)",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX28",
    "Types": "Dry Chemical",
    "Weight (lb)": 0,
    "Area": "WH (Construction zone)",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX29",
    "Types": "Dry Chemical",
    "Weight (lb)": 0,
    "Area": "WH (Construction zone)",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX30",
    "Types": "Dry Chemical",
    "Weight (lb)": 0,
    "Area": "WH (Construction zone)",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX31",
    "Types": "Dry Chemical",
    "Weight (lb)": 0,
    "Area": "WH (Construction zone)",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX32",
    "Types": "Dry Chemical",
    "Weight (lb)": 0,
    "Area": "WH (Construction zone)",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX33",
    "Types": "Dry Chemical",
    "Weight (lb)": 0,
    "Area": "WH (Construction zone)",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX34",
    "Types": "Dry Chemical",
    "Weight (lb)": 20,
    "Area": "Charging station WH",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX35",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 15,
    "Area": "Charging station WH",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX36",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 15,
    "Area": "Charging station WH",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX37",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH loading",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX38",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH loading",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX39",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH loading",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX40",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH (Construction zone)",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX41",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH (Construction zone)",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX42",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH (Construction zone)",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX43",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "WH (Construction zone)",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX44",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Pack",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX45",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Pack",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX46",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Pack",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX47",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Pack",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX48",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Pack",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX49",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Pack",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX50",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Pack",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX51",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Pack",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX52",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Mix",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX53",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Mix",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX54",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Mix",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX55",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Mix",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX56",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 1 Mix",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX57",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2019",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "7ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX58",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX59",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX60",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2019",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "7ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX61",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX62",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX63",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2019",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "7ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX64",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX65",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2009",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "17ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX66",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2006",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "20ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX67",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX68",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2019",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "7ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX69",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX70",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX71",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2019",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "7ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX72",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Mix",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX73",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX74",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX75",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX76",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX77",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX78",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX79",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2019",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "7ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX80",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2018",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX81",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2019",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "7ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX82",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "PD 2 Pack",
    "Inuse": "01/01/2017",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "9ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX83",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "AHU 3rd Floor",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX84",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "AHU 3rd Floor",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX85",
    "Types": "Dry Chemical",
    "Weight (lb)": 15,
    "Area": "Smoking room",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX86",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 15,
    "Area": "Charging station AGV PD1",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX87",
    "Types": "CO2",
    "Weight (lb)": 0,
    "Area": "Remove",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX88",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": null,
    "Area": "Emergency eyewash station Behind Building 1 (UT)",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX89",
    "Types": "Low-pressure water formula",
    "Weight (lb)": 10,
    "Area": "First Aid Room",
    "Inuse": "01/01/2025",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "1ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX90",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Public Relations Board (HR)",
    "Inuse": "01/01/2022",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "4ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX91",
    "Types": "Low-pressure water formula",
    "Weight (lb)": 10,
    "Area": "Office 1st Floor",
    "Inuse": "01/01/2025",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "1ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX92",
    "Types": "Low-pressure water formula",
    "Weight (lb)": 10,
    "Area": "Male toilet (Emp)",
    "Inuse": "01/01/2025",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "1ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX93",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "Male locker room",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX94",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "Washroom PD1",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX95",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "Female locker room",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX96",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "Training Room",
    "Inuse": "01/01/2024",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "2ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX97",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "Training Room",
    "Inuse": "01/01/2025",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "1ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX98",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "Doddy PD1 ",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX99",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "Doddy PD1 ",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX100",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "End of line PD2",
    "Inuse": "01/01/2004",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "22ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX101",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "Waste compactor building 1",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX102",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "Fire Pump Room building 1",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX103",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "Transformer building 1 room ",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX104",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "Transformer building 1 room ",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX105",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Garbage House",
    "Inuse": null,
    "Lastcheck": "2026-09-29 17:45",
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": "Ready",
    "TankStatus": true,
    "Exptank": null,
    "PicTank": "uploads/tanks/EX105_PicTank_QRCode_JDE_Peets_scml.png",
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX106",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Garbage House",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX107",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "Fire Pump Room building 2",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX108",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "AHU",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX109",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "AHU",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX110",
    "Types": "Halocarbon Clean Agent",
    "Weight (lb)": 10,
    "Area": "Air Com ",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX111",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "Dust Collector Room PD1",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX112",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Generator room building 2",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX113",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Security guard",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX114",
    "Types": "Dry Chemical",
    "Weight (lb)": 10,
    "Area": "Spare Parts Room",
    "Inuse": null,
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": null,
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "EX115",
    "Types": "CO2",
    "Weight (lb)": 10,
    "Area": "Cold room building 1",
    "Inuse": "01/01/2018",
    "Lastcheck": "2026-09-29 16:17",
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": "Ready",
    "TankStatus": true,
    "Exptank": "8ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  },
  {
    "FireTank": "Ex116",
    "Types": null,
    "Weight (lb)": null,
    "Area": null,
    "Inuse": "01/01/2021",
    "Lastcheck": 2026,
    "Tankcheck": "เช็คแล้ว",
    "ReadyorNot": null,
    "TankStatus": true,
    "Exptank": "5ปี",
    "PicTank": null,
    "PicArea": null,
    "Inspector": null
  }
];
