-- ============================================================
-- Cloudflare D1 Database Schema & Initial Data for JDEProject
-- Database: jdefireextinguisher (ID: aec6a610-ec7c-49c4-aecf-5fe39cc05034)
-- ============================================================

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS users (
  username TEXT PRIMARY KEY,
  password TEXT,
  rank TEXT DEFAULT 'P1',
  permit_do INTEGER DEFAULT 1,
  em_name TEXT
);

CREATE TABLE IF NOT EXISTS pending_users (
  username TEXT PRIMARY KEY,
  password TEXT,
  em_name TEXT,
  rank TEXT DEFAULT 'P1',
  permit_do INTEGER DEFAULT 1,
  registered_at TEXT
);

CREATE TABLE IF NOT EXISTS tanks (
  fire_tank TEXT PRIMARY KEY,
  types TEXT,
  weight REAL,
  area TEXT,
  inuse TEXT,
  lastcheck TEXT,
  tankcheck TEXT DEFAULT 'ยังไม่เช็ค',
  ready_or_not TEXT DEFAULT 'Not Ready',
  tank_status INTEGER DEFAULT 0,
  exptank TEXT,
  pic_tank TEXT,
  pic_area TEXT,
  inspector TEXT,
  responsible TEXT,
  remark TEXT
);

-- 2. Seed Default Users
INSERT OR REPLACE INTO users (username, password, rank, permit_do, em_name) VALUES
('johporadmin', 'Admin0123456789', 'P3', 3, 'Administrator'),
('LeaderLinePD1', 'PD1', 'P1', 1, 'Jort');

-- 3. Seed Initial Tanks
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX01', 'Low-pressure water formula', 10, 'Solar WH', '01/01/2022', '2026-09-29 17:57', 'เช็คแล้ว', 'Ready', 1, '4ปี', 'uploads/tanks/EX01_PicTank_QRCode_JDE_Peets_scml.png', NULL, 'Jort', NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX02', 'Dry Chemical', 20, 'LPG station', NULL, '2026-09-29 18:38', 'เช็คแล้ว', 'Ready', 1, NULL, 'uploads/tanks/EX02_PicTank_QRCode_JDE_Peets_scml.png', NULL, 'Jort', NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX03', 'Dry Chemical', 10, 'Checker (Production)', '01/01/2012', '2026-09-29 16:10', 'เช็คแล้ว', 'Ready', 1, '14ปี', 'uploads/tanks/EX03_PicTank_QRCode_JDE_Peets_scml.png', NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX04', 'Dry Chemical', 10, 'Equipment Washing Room', '01/01/2013', '2026', 'เช็คแล้ว', 'Not Ready', 1, '13ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX05', 'Dry Chemical', 10, 'Hot work (in)', '01/01/2016', '2026', 'เช็คแล้ว', 'Not Ready', 1, '10ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX06', 'Dry Chemical', 10, 'Hot work', '01/01/2019', '2026', 'เช็คแล้ว', 'Not Ready', 1, '7ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX07', 'Dry Chemical', 10, 'Washroom PD2', '01/01/2017', '2026', 'เช็คแล้ว', 'Not Ready', 1, '9ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX08', 'Dry Chemical', 20, 'Rework PD1', '01/01/2005', '2026', 'เช็คแล้ว', 'Not Ready', 1, '21ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX09', 'Dry Chemical', 15, 'Hazardous waste point PD1', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX10', 'CO2', 10, 'SAP PD1', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX11', 'Dry Chemical', 10, 'MDB2', '01/01/2019', '2026', 'เช็คแล้ว', 'Not Ready', 1, '7ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX12', 'Halocarbon Clean Agent', 20, 'MDB2 (in)', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX13', 'Dry Chemical', 15, 'Canteen', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX14', 'Low-pressure water formula', 10, 'Office 2nd Floor', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX15', 'Low-pressure water formula', 10, 'Office 2nd Floor', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX16', 'Dry Chemical', 20, 'Document room 3rd Floor', '01/01/2006', '2026-09-29 17:54', 'เช็คแล้ว', 'Ready', 1, '20ปี', 'uploads/tanks/EX16_PicTank_QRCode_JDE_Peets_scml.png', NULL, 'Jort', NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX17', 'Halocarbon Clean Agent', 10, '3rd Floor', '01/01/2021', '2026', 'เช็คแล้ว', 'Not Ready', 1, '5ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX18', 'CO2', NULL, 'AHU 3rd Floor', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX19', 'Dry Chemical', 15, 'WH ', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX20', 'Low-pressure water formula', 10, 'WH gennerator solar', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX21', 'Dry Chemical', 15, 'WH ', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX22', 'Dry Chemical', 15, 'WH ', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX23', 'Dry Chemical', 15, 'WH ', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX24', 'Dry Chemical', 15, 'WH ', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX25', 'Dry Chemical', 15, 'WH Bluk loading', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX26', 'Dry Chemical', NULL, 'WH (Construction zone)', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX27', 'Dry Chemical', NULL, 'WH (Construction zone)', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX28', 'Dry Chemical', NULL, 'WH (Construction zone)', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX29', 'Dry Chemical', NULL, 'WH (Construction zone)', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX30', 'Dry Chemical', NULL, 'WH (Construction zone)', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX31', 'Dry Chemical', NULL, 'WH (Construction zone)', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX32', 'Dry Chemical', NULL, 'WH (Construction zone)', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX33', 'Dry Chemical', NULL, 'WH (Construction zone)', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX34', 'Dry Chemical', 20, 'Charging station WH', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX35', 'Halocarbon Clean Agent', 15, 'Charging station WH', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX36', 'Halocarbon Clean Agent', 15, 'Charging station WH', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX37', 'Dry Chemical', 15, 'WH loading', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX38', 'Dry Chemical', 15, 'WH loading', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX39', 'Dry Chemical', 15, 'WH loading', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX40', 'Dry Chemical', 15, 'WH (Construction zone)', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX41', 'Dry Chemical', 15, 'WH (Construction zone)', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX42', 'Dry Chemical', 15, 'WH (Construction zone)', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX43', 'Dry Chemical', 15, 'WH (Construction zone)', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX44', 'CO2', 10, 'PD 1 Pack', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX45', 'CO2', 10, 'PD 1 Pack', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX46', 'CO2', 10, 'PD 1 Pack', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX47', 'CO2', 10, 'PD 1 Pack', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX48', 'CO2', 10, 'PD 1 Pack', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX49', 'CO2', 10, 'PD 1 Pack', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX50', 'CO2', 10, 'PD 1 Pack', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX51', 'CO2', 10, 'PD 1 Pack', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX52', 'CO2', 10, 'PD 1 Mix', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX53', 'CO2', 10, 'PD 1 Mix', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX54', 'CO2', 10, 'PD 1 Mix', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX55', 'CO2', 10, 'PD 1 Mix', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX56', 'CO2', 10, 'PD 1 Mix', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX57', 'Halocarbon Clean Agent', 10, 'PD 2 Mix', '01/01/2019', '2026', 'เช็คแล้ว', 'Not Ready', 1, '7ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX58', 'CO2', 10, 'PD 2 Mix', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX59', 'Halocarbon Clean Agent', 10, 'PD 2 Mix', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX60', 'CO2', 10, 'PD 2 Mix', '01/01/2019', '2026', 'เช็คแล้ว', 'Not Ready', 1, '7ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX61', 'CO2', 10, 'PD 2 Mix', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX62', 'CO2', 10, 'PD 2 Mix', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX63', 'Halocarbon Clean Agent', 10, 'PD 2 Mix', '01/01/2019', '2026', 'เช็คแล้ว', 'Not Ready', 1, '7ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX64', 'CO2', 10, 'PD 2 Mix', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX65', 'CO2', 10, 'PD 2 Mix', '01/01/2009', '2026', 'เช็คแล้ว', 'Not Ready', 1, '17ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX66', 'CO2', 10, 'PD 2 Mix', '01/01/2006', '2026', 'เช็คแล้ว', 'Not Ready', 1, '20ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX67', 'CO2', 10, 'PD 2 Mix', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX68', 'Halocarbon Clean Agent', 10, 'PD 2 Mix', '01/01/2019', '2026', 'เช็คแล้ว', 'Not Ready', 1, '7ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX69', 'CO2', 10, 'PD 2 Mix', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX70', 'CO2', 10, 'PD 2 Mix', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX71', 'Halocarbon Clean Agent', 10, 'PD 2 Mix', '01/01/2019', '2026', 'เช็คแล้ว', 'Not Ready', 1, '7ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX72', 'CO2', 10, 'PD 2 Mix', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX73', 'CO2', 10, 'PD 2 Pack', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX74', 'CO2', 10, 'PD 2 Pack', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX75', 'CO2', 10, 'PD 2 Pack', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX76', 'CO2', 10, 'PD 2 Pack', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX77', 'CO2', 10, 'PD 2 Pack', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX78', 'CO2', 10, 'PD 2 Pack', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX79', 'Halocarbon Clean Agent', 10, 'PD 2 Pack', '01/01/2019', '2026', 'เช็คแล้ว', 'Not Ready', 1, '7ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX80', 'CO2', 10, 'PD 2 Pack', '01/01/2018', '2026', 'เช็คแล้ว', 'Not Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX81', 'Halocarbon Clean Agent', 10, 'PD 2 Pack', '01/01/2019', '2026', 'เช็คแล้ว', 'Not Ready', 1, '7ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX82', 'CO2', 10, 'PD 2 Pack', '01/01/2017', '2026', 'เช็คแล้ว', 'Not Ready', 1, '9ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX83', 'Dry Chemical', 10, 'AHU 3rd Floor', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX84', 'Dry Chemical', 10, 'AHU 3rd Floor', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX85', 'Dry Chemical', 15, 'Smoking room', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX86', 'Halocarbon Clean Agent', 15, 'Charging station AGV PD1', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX87', 'CO2', NULL, 'Remove', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX88', 'Halocarbon Clean Agent', NULL, 'Emergency eyewash station Behind Building 1 (UT)', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX89', 'Low-pressure water formula', 10, 'First Aid Room', '01/01/2025', '2026', 'เช็คแล้ว', 'Not Ready', 1, '1ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX90', 'Dry Chemical', 10, 'Public Relations Board (HR)', '01/01/2022', '2026', 'เช็คแล้ว', 'Not Ready', 1, '4ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX91', 'Low-pressure water formula', 10, 'Office 1st Floor', '01/01/2025', '2026', 'เช็คแล้ว', 'Not Ready', 1, '1ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX92', 'Low-pressure water formula', 10, 'Male toilet (Emp)', '01/01/2025', '2026', 'เช็คแล้ว', 'Not Ready', 1, '1ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX93', 'CO2', 10, 'Male locker room', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX94', 'CO2', 10, 'Washroom PD1', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX95', 'CO2', 10, 'Female locker room', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX96', 'CO2', 10, 'Training Room', '01/01/2024', '2026', 'เช็คแล้ว', 'Not Ready', 1, '2ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX97', 'CO2', 10, 'Training Room', '01/01/2025', '2026', 'เช็คแล้ว', 'Not Ready', 1, '1ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX98', 'CO2', 10, 'Doddy PD1 ', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX99', 'CO2', 10, 'Doddy PD1 ', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX100', 'Dry Chemical', 10, 'End of line PD2', '01/01/2004', '2026', 'เช็คแล้ว', 'Not Ready', 1, '22ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX101', 'Halocarbon Clean Agent', 10, 'Waste compactor building 1', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX102', 'Halocarbon Clean Agent', 10, 'Fire Pump Room building 1', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX103', 'Halocarbon Clean Agent', 10, 'Transformer building 1 room ', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX104', 'Halocarbon Clean Agent', 10, 'Transformer building 1 room ', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX105', 'Dry Chemical', 10, 'Garbage House', NULL, '2026-09-29 17:45', 'เช็คแล้ว', 'Ready', 1, NULL, 'uploads/tanks/EX105_PicTank_QRCode_JDE_Peets_scml.png', NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX106', 'Dry Chemical', 10, 'Garbage House', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX107', 'Halocarbon Clean Agent', 10, 'Fire Pump Room building 2', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX108', 'CO2', 10, 'AHU', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX109', 'CO2', 10, 'AHU', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX110', 'Halocarbon Clean Agent', 10, 'Air Com ', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX111', 'CO2', 10, 'Dust Collector Room PD1', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX112', 'Dry Chemical', 10, 'Generator room building 2', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX113', 'Dry Chemical', 10, 'Security guard', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX114', 'Dry Chemical', 10, 'Spare Parts Room', NULL, '2026', 'เช็คแล้ว', 'Not Ready', 1, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('EX115', 'CO2', 10, 'Cold room building 1', '01/01/2018', '2026-09-29 16:17', 'เช็คแล้ว', 'Ready', 1, '8ปี', NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO tanks (fire_tank, types, weight, area, inuse, lastcheck, tankcheck, ready_or_not, tank_status, exptank, pic_tank, pic_area, inspector, responsible, remark) VALUES ('Ex116', '', NULL, '', '01/01/2021', '2026', 'เช็คแล้ว', 'Not Ready', 1, '5ปี', NULL, NULL, NULL, NULL, NULL);